In [1]:
import numpy as np 
import pandas as pd

In [54]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

## Working w Dates

In [9]:
date = date.drop(columns=['product_id','city_id','orders'])
date.head()

         date
0  2019-12-10
1  2018-08-15
2  2018-10-23
3  2019-08-17
4  2019-01-06

In [12]:
# First Always Check the data type of date col , So u can use all the date features
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
dtypes: object(1)
memory usage: 7.9+ KB

In [13]:
# converting str(object) to datetime data type 
date['date'] = pd.to_datetime(date['date'])

In [14]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 7.9 KB

### Extract Year

In [17]:
date['date_year'] = date['date'].dt.year

date.sample(5)

          date  date_year
32  2018-10-23       2018
7   2019-03-27       2019
439 2019-11-21       2019
66  2019-01-26       2019
265 2019-04-28       2019

### Extract Month

In [18]:
date['date_month'] = date['date'].dt.month

date.sample(5)

          date  date_year  date_month
741 2019-11-10       2019          11
852 2018-09-04       2018           9
985 2018-12-08       2018          12
515 2019-06-22       2019           6
499 2018-09-28       2018           9

### Extract Days

In [30]:
date['date_day'] = date['date'].dt.day

date.sample(5)

,date,date_year,date_month,date_date,date_day,date_wek,date_week,date_day_name,date_dow_name,date_is_weekend
260,2019-02-04,2019,2,2019-02-04,4,0,0,Monday,Monday,0
662,2019-07-08,2019,7,2019-07-08,8,0,0,Monday,Monday,0
429,2019-11-11,2019,11,2019-11-11,11,0,0,Monday,Monday,0
244,2019-11-13,2019,11,2019-11-13,13,2,2,Wednesday,Wednesday,0
655,2019-10-07,2019,10,2019-10-07,7,0,0,Monday,Monday,0

In [24]:
# Day of the Week
date['date_week'] = date['date'].dt.dayofweek

date.sample(5)

,date,date_year,date_month,date_date,date_day,date_wek,date_week
162,2019-11-17,2019,11,2019-11-17,17,6,6
759,2019-11-23,2019,11,2019-11-23,23,5,5
946,2018-11-10,2018,11,2018-11-10,10,5,5
760,2019-10-31,2019,10,2019-10-31,31,3,3
446,2019-06-28,2019,6,2019-06-28,28,4,4

In [31]:
# Day of the week name 
date['date_dow_name'] = date['date'].dt.day_name()

date.sample(5)

,date,date_year,date_month,date_date,date_day,date_wek,date_week,date_day_name,date_dow_name,date_is_weekend
899,2019-07-12,2019,7,2019-07-12,12,4,4,Friday,Friday,0
122,2019-12-04,2019,12,2019-12-04,4,2,2,Wednesday,Wednesday,0
120,2018-11-19,2018,11,2018-11-19,19,0,0,Monday,Monday,0
945,2018-07-17,2018,7,2018-07-17,17,1,1,Tuesday,Tuesday,0
329,2019-03-05,2019,3,2019-03-05,5,1,1,Tuesday,Tuesday,0

In [29]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)   # Used Numpy Logic for extraction
date.sample(5)

,date,date_year,date_month,date_date,date_day,date_wek,date_week,date_day_name,date_dow_name,date_is_weekend
130,2019-07-12,2019,7,2019-07-12,12,4,4,Friday,Friday,0
703,2019-08-02,2019,8,2019-08-02,2,4,4,Friday,Friday,0
886,2018-09-05,2018,9,2018-09-05,5,2,2,Wednesday,Wednesday,0
806,2019-07-13,2019,7,2019-07-13,13,5,5,Saturday,Saturday,1
697,2019-10-10,2019,10,2019-10-10,10,3,3,Thursday,Thursday,0

### Extract Week of the Year

In [37]:
date['Year_date_week'] = date['date'].dt.isocalendar().week
date.sample(5)

,date,date_year,date_month,date_date,date_day,date_wek,date_dow_name,date_is_weekend,Year_date_week
589,2019-01-02,2019,1,2019-01-02,2,2,Wednesday,0,1
383,2019-11-28,2019,11,2019-11-28,28,3,Thursday,0,48
45,2019-07-01,2019,7,2019-07-01,1,0,Monday,0,27
445,2019-10-14,2019,10,2019-10-14,14,0,Monday,0,42
313,2018-12-29,2018,12,2018-12-29,29,5,Saturday,1,52

In [36]:
# by mistakly i have extracted 2 duplicate cols , thats why i am dropping them
date = date.drop(columns=['date_week','date_day_name'])

### Extract Quarter

In [38]:
date['quarter'] = date['date'].dt.quarter
date.sample(5)

,date,date_year,date_month,date_date,date_day,date_wek,date_dow_name,date_is_weekend,Year_date_week,quarter
811,2018-11-03,2018,11,2018-11-03,3,5,Saturday,1,44,4
669,2018-10-31,2018,10,2018-10-31,31,2,Wednesday,0,44,4
49,2019-07-24,2019,7,2019-07-24,24,2,Wednesday,0,30,3
598,2018-09-07,2018,9,2018-09-07,7,4,Friday,0,36,3
47,2018-12-11,2018,12,2018-12-11,11,1,Tuesday,0,50,4

### Extract Semester

In [39]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

In [40]:
date.sample(5)

,date,date_year,date_month,date_date,date_day,date_wek,date_dow_name,date_is_weekend,Year_date_week,quarter,semester
734,2018-12-21,2018,12,2018-12-21,21,4,Friday,0,51,4,2
815,2019-12-08,2019,12,2019-12-08,8,6,Sunday,1,49,4,2
341,2019-05-04,2019,5,2019-05-04,4,5,Saturday,1,18,2,1
890,2018-09-03,2018,9,2018-09-03,3,0,Monday,0,36,3,2
832,2019-01-11,2019,1,2019-01-11,11,4,Friday,0,2,1,1

### Extract Time elapsed between dates

In [44]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 5, 4, 13, 19, 57, 749932)

In [46]:
# we get the diff between current time the Value time
today - date['date']

0     2337 days 13:19:57.749932
1     2819 days 13:19:57.749932
2     2750 days 13:19:57.749932
3     2452 days 13:19:57.749932
4     2675 days 13:19:57.749932
                 ...
995   2765 days 13:19:57.749932
996   2706 days 13:19:57.749932
997   2554 days 13:19:57.749932
998   2619 days 13:19:57.749932
999   2393 days 13:19:57.749932
Name: date, Length: 1000, dtype: timedelta64[ns]

In [48]:
#  To get the no. of days passed
(today - date['date']).dt.days

0      2337
1      2819
2      2750
3      2452
4      2675
       ...
995    2765
996    2706
997    2554
998    2619
999    2393
Name: date, Length: 1000, dtype: int64

In [51]:
# Weeks passed
np.round((today -date['date']) / np.timedelta64(1, 'W'),0)

0      334.0
1      403.0
2      393.0
3      350.0
4      382.0
       ...
995    395.0
996    387.0
997    365.0
998    374.0
999    342.0
Name: date, Length: 1000, dtype: float64

## Working W Time

In [55]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [56]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [57]:
# Convert obj to datetime
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [58]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

### Extract Time part

In [59]:

time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

### Time difference

In [60]:
today - time['date']

0     4523 days 12:29:57.749932
1     4387 days 13:39:57.749932
2     4873 days 12:58:57.749932
3     4175 days 12:48:57.749932
4     4572 days 14:08:57.749932
                 ...
995   5162 days 12:29:57.749932
996   4483 days 14:05:57.749932
997   4948 days 13:42:57.749932
998   5064 days 13:45:57.749932
999   4336 days 13:54:57.749932
Name: date, Length: 1000, dtype: timedelta64[ns]

In [61]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.908322e+08
1      3.790860e+08
2      4.210739e+08
3      3.607661e+08
4      3.950717e+08
           ...
995    4.460418e+08
996    3.873820e+08
997    4.275566e+08
998    4.375792e+08
999    3.746805e+08
Name: date, Length: 1000, dtype: float64

In [62]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.513870e+06
1      6.318100e+06
2      7.017899e+06
3      6.012769e+06
4      6.584529e+06
           ...
995    7.434030e+06
996    6.456366e+06
997    7.125943e+06
998    7.292986e+06
999    6.244675e+06
Name: date, Length: 1000, dtype: float64

In [63]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      108564.499375
1      105301.666042
2      116964.982708
3      100212.816042
4      109742.149375
           ...
995    123900.499375
996    107606.099375
997    118765.716042
998    121549.766042
999    104077.916042
Name: date, Length: 1000, dtype: float64